name: Develop terminal Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  CARGO_TERM_COLOR: always

jobs:
  dev:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      # - name: Run formatter
      - name: Run fmt
        run: cargo fmt --all -- --check
      
      # - name: Run Linter
      - name: Run clippy
        run: cargo clippy --all -- -D warnings

      # - name: Run Test
      - name: Run test
        run: cargo test --verbose

      # - name: Run Build
      - name: Run build
        run: cargo build --verbose