name: TypeScript Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]

jobs:
  tsc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Deno fmt
        run: deno fmt --check
    
      - name: Run linter
        run: deno lint
        
      - name: Run tests
        run: deno test -A